import ThemeProvider from "@/components/theme-provider";
import "./globals.css";
import type { Metadata } from "next";
import clsx from "clsx";
import { NavBar } from "@/components/navbar/navbar";
import { poppins } from "@/lib/fonts";
import { getServerSession } from "next-auth";

export const metadata: Metadata = {
  title: "Jackpot | Win Your Lottery Today",
  description: "Generated by create next app",
  icons: {},
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html
      lang="en"
      className="light"
      style={{ colorScheme: "light" }}
      suppressHydrationWarning
    >
      <body
        className={clsx(
          poppins.className,
          "bg-white dark:bg-black text-black dark:text-white transition-colors"
        )}
      >
        {}
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <NavBar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
